name: Package to Test PyPi

on: workflow_dispatch

permissions:
  contents: read

jobs:
  test-pypi:
    runs-on: ubuntu-latest
    environment:
      name: test-pypi-upload
      url: https://test.pypi.org/p/mapof-roommates
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:    
        verbose: true
        repository-url: https://test.pypi.org/legacy/
